name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Homebrew
        run: |
          brew update
          brew install check

      - name: Build project
        run: make

      - name: Run tests
        run: make test
