name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Checkout code
        uses: actions/checkout@v3
        
        with:
          ref: ${{ github.ref }}

      - name: Set up Homebrew
        run: |
          brew update
          brew install check

      - name: Build project
        working-directory: ./src
        run: make

      - name: Run tests
        working-directory: ./src
        run: make test
